version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: go_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"
    command: ["sh", "-c", "sleep 30 && ./app"]

volumes:
  db_data:
